"""one more value

Revision ID: 75bf22858c05
Revises: baa54778a33a
Create Date: 2022-04-24 10:04:45.112729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bf22858c05'
down_revision = 'baa54778a33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_plan_sms_usage', sa.Column('rate_plan_zone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rate_plan_sms_usage', 'rate_plan_zone', ['rate_plan_zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rate_plan_sms_usage', type_='foreignkey')
    op.drop_column('rate_plan_sms_usage', 'rate_plan_zone_id')
    # ### end Alembic commands ###
