"""one more value

Revision ID: baa54778a33a
Revises: 
Create Date: 2022-04-24 10:01:52.547189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa54778a33a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataUsageToDate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctdDataUsage', sa.BIGINT(), nullable=True),
    sa.Column('ctdSMSUsage', sa.BIGINT(), nullable=True),
    sa.Column('ctdVoiceUsage', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jasper_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_plan_sms_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_default_rating', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jasper_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('api_key', sa.String(length=256), nullable=True),
    sa.Column('jasper_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jasper_account_id'], ['jasper_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('subscription_charge', sa.Integer(), nullable=True),
    sa.Column('number_of_tires', sa.Integer(), nullable=True),
    sa.Column('tier_treatment', sa.String(length=256), nullable=True),
    sa.Column('expire_term_based_on_usage', sa.Boolean(), nullable=True),
    sa.Column('lengthOfTerm', sa.Integer(), nullable=True),
    sa.Column('subscriptionChargeUnit', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('jasper_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jasper_account_id'], ['jasper_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_plan_tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=True),
    sa.Column('subscriber_threshold', sa.Integer(), nullable=True),
    sa.Column('subscriber_capacity', sa.String(length=256), nullable=True),
    sa.Column('per_subscriber_charge', sa.Integer(), nullable=True),
    sa.Column('rate_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_plan_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=256), nullable=True),
    sa.Column('report_overage_as_roaming', sa.Boolean(), nullable=True),
    sa.Column('rate_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_plan_data_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_default_rating', sa.Boolean(), nullable=True),
    sa.Column('usage_limit_unit', sa.String(length=256), nullable=True),
    sa.Column('rate_plan_zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_plan_zone_id'], ['rate_plan_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_plan_data_usage')
    op.drop_table('rate_plan_zone')
    op.drop_table('rate_plan_tier')
    op.drop_table('rate_plan')
    op.drop_table('jasper_credential')
    op.drop_table('rate_plan_sms_usage')
    op.drop_table('jasper_account')
    op.drop_table('DataUsageToDate')
    # ### end Alembic commands ###
