"""one more value

Revision ID: d7a23e452f06
Revises: 75bf22858c05
Create Date: 2022-04-24 10:11:21.843552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a23e452f06'
down_revision = '75bf22858c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_plan_voice_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_default_rating', sa.Boolean(), nullable=True),
    sa.Column('rate_plan_zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_plan_zone_id'], ['rate_plan_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_plan_voice_usage')
    # ### end Alembic commands ###
