"""one more value

Revision ID: f88f32a90aff
Revises: d7a23e452f06
Create Date: 2022-04-24 17:41:29.724268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88f32a90aff'
down_revision = 'd7a23e452f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_plan', sa.Column('account_name', sa.String(length=256), nullable=True))
    op.add_column('rate_plan', sa.Column('account_id', sa.String(length=256), nullable=True))
    op.add_column('rate_plan_data_usage', sa.Column('included_data', sa.BIGINT(), nullable=True))
    op.add_column('rate_plan_data_usage', sa.Column('included_data_unit', sa.String(length=2), nullable=True))
    op.add_column('rate_plan_data_usage', sa.Column('zone_usage_limit_unit', sa.String(length=256), nullable=True))
    op.add_column('rate_plan_data_usage', sa.Column('bulk_overage_enabled', sa.Boolean(), nullable=True))
    op.add_column('rate_plan_data_usage', sa.Column('use_these_data_rounding_settings_for_all_zones', sa.Boolean(), nullable=True))
    op.add_column('rate_plan_data_usage', sa.Column('data_rounding_unit', sa.String(length=256), nullable=True))
    op.add_column('rate_plan_data_usage', sa.Column('data_rounding_frequency', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_plan_data_usage', 'data_rounding_frequency')
    op.drop_column('rate_plan_data_usage', 'data_rounding_unit')
    op.drop_column('rate_plan_data_usage', 'use_these_data_rounding_settings_for_all_zones')
    op.drop_column('rate_plan_data_usage', 'bulk_overage_enabled')
    op.drop_column('rate_plan_data_usage', 'zone_usage_limit_unit')
    op.drop_column('rate_plan_data_usage', 'included_data_unit')
    op.drop_column('rate_plan_data_usage', 'included_data')
    op.drop_column('rate_plan', 'account_id')
    op.drop_column('rate_plan', 'account_name')
    # ### end Alembic commands ###
